deuzu_request_collector_collect:
    path: /
    methods: ['GET', 'HEAD']
    defaults: { _controller: DeuzuRequestCollectorBundle:Default:collect }

deuzu_request_collector_index:
    path: /inspect
    methods: ['GET', 'HEAD']
    defaults: { _controller: DeuzuRequestCollectorBundle:Default:index }
